from .data import *
from .generate_matrix import *
from .apply_boundary_conditions import *
from .initialise_conditions import *
from .solve import *
from .draw_temperature import *
from .calculate_deformation import *
from .draw_deformation import *
from .calculate_flow import *
from .draw_flow import *
from .calculate_healing import *
from .draw_healing import *